CREATE TABLE IF NOT EXISTS auth_failures (
  email VARCHAR(255) PRIMARY KEY,
  fails INT NOT NULL DEFAULT 0,
  last_fail TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  locked_until TIMESTAMP NULL
);
